### ISSUE TITLE
questions about Conf-CE loss

### ISSUE THREAD

**Issue by Darcy103** [yyliu01/PS-MT#1]
I recently read your paper and it's a great job. I have a question about the Conf-CE loss in the paper. Can you explain what the c(w) formula means? I confused y~ and y^ in the c(w), formula(4), figure 2.
![question1](https://user-images.githubusercontent.com/80041285/162619516-3c96e244-be51-4f5d-bf08-e6321c5c750d.jpg)
![question2](https://user-images.githubusercontent.com/80041285/162619520-57a11ec4-0f45-4bb1-94f0-3f0f8ab419b2.PNG)

**Comment by yyliu01** [comment]
you're welcome.
