### ISSUE TITLE
before_start.md error？

### ISSUE THREAD

**Issue by Yan1026** [yyliu01/PS-MT#11]
Hi,thank you for your great work!

In **Cityscapes Setting**,you said that   

run the scripts with

```
# -l -> labelled_num; -g -> gpus; -b -> resnet backbone;
./scripts/train_voc_hq.sh -l 372 -g 2 -b 50
```
Should it be `./scripts/train_city.sh -l 372 -g 2 -b 50` here?

**Comment by yyliu01** [comment]
Thanks a lot for report that issue! 
I have fixed it now.
