### ISSUE TITLE
Cityscapes dataset 

### ISSUE THREAD

**Issue by gufan-d** [yyliu01/PS-MT#12]
Hi!Thank you for the contribution!

Could you provide processed cityscape dataset?I want to use the same dataset to train.

Thanks!

**Comment by yyliu01** [comment]
Hi, thanks for your interest.

The pre-process in here means convert the labelID to trainID (from 33 to 19), and I think our training data is totally same as the CPS (https://pkueducn-my.sharepoint.com/personal/pkucxk_pku_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpkucxk%5Fpku%5Fedu%5Fcn%2FDocuments%2FDATA&ga=1). 

Regards,
Yuyuan
