### ISSUE TITLE
Questions about the training environment

### ISSUE THREAD

**Issue by DeepHM** [yyliu01/PS-MT#15]
Hello.
Can I know the gpu information (gpu name(type), number of gpu, and memory usage of gpu) and training time in your experiments?

If possible, I would like to know roughly about VOC and Cicyscapes, respectively.
(especially training time and gpu memory usage)

Thank you !

**Comment by yyliu01** [comment]
Thanks for your interest.

We've provided all the training details via the wandb log. For example, in Pascal VOC12 experiment, you can find the hardware information, training time in https://wandb.ai/pyedog1976/PS-MT(VOC12)/runs/177s76t6/overview?workspace=user-pyedog1976. Also, the training logs in https://wandb.ai/pyedog1976/PS-MT(VOC12)/runs/177s76t6/logs?workspace=user-pyedog1976 and system history in https://wandb.ai/pyedog1976/PS-MT(VOC12)/runs/177s76t6/system?workspace=user-pyedog1976.

Besides, you can find all the information in the wandb log of Cityscapes (which is provided in this repo as well). 

Cheers,
Yuyuan

**Comment by DeepHM** [comment]
Thank you!
