### ISSUE TITLE
T-VAT

### ISSUE THREAD

**Issue by manongXT** [yyliu01/PS-MT#18]
Hello, I would like to know where is your T-VAT module code? Please help me.

**Comment by yyliu01** [comment]
Thanks for your interest, and I apologise for the late response.

The T-VAT related code is in https://github.com/yyliu01/PS-MT/blob/61d566e5670b900087a85f1e6021584c168122a9/VocCode/Model/Deeplabv3_plus/encoder_decoder.py#L59.

Cheers,
Yuyuan
