### ISSUE TITLE
sliding evaluation

### ISSUE THREAD

**Issue by NJNUCS** [yyliu01/PS-MT#19]
Hello, thank you for your excellent work, I read your paper, I have a place is not very clear, is the experiment mentioned in the sliding evaluation is what it means, hope to get your reply, thank you!

**Comment by yyliu01** [comment]
Sorry, I cannot understand your question.

The sliding evaluation is only for the Cityscapes dataset to deal with the high-resolution driving scenes, and all the hyper-parameters are based on the CPS (https://github.com/charlesCXK/TorchSemiSeg/tree/main/exp.city/city8.res50v3%2B.CPS%2BCutMix).

Please let me know if you are not satisfied with the answer.

**Comment by NJNUCS** [comment]
Thank you for your timely response

**Comment by NJNUCS** [comment]
Hello, I would like to ask, what is the function of self.assist_mask_calculate() function in line 224 of train.py?

**Comment by NJNUCS** [comment]
Sorry, I have one more question. After the teacher-student model is trained, shouldn't the student model be used for validation, but here you are using the average of the teacher model for validation.What are the benefits of doing this?

**Comment by yyliu01** [comment]
Hi @NJNUCS 

I apologise that I didn't see your question on time. In our cases, we experimentally find that the dual teachers inference are slightly better than the students (maybe the more stable prediction can be the reason). Please note: we utilise single-teacher inference in cityscape for efficiency.
