### ISSUE TITLE
About DDP

### ISSUE THREAD

**Issue by Yan1026** [yyliu01/PS-MT#20]
Hi!Sorry to bother you again.

I try to train the model,GPU memory usage as follow：
`
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory | 
|        ID   ID                                                                              Usage      |
|======================================================================|

|    5   N/A  N/A     26598      C   ...da/envs/ps-mt/bin/python3     2885MiB |
|    5   N/A  N/A     26599      C   ...da/envs/ps-mt/bin/python3     1387MiB |
|    5   N/A  N/A     26600      C   ...da/envs/ps-mt/bin/python3     1387MiB |
|    5   N/A  N/A     26601      C   ...da/envs/ps-mt/bin/python3     1387MiB |
|    6   N/A  N/A     26599      C   ...da/envs/ps-mt/bin/python3     2889MiB |
|    7   N/A  N/A     26600      C   ...da/envs/ps-mt/bin/python3     2889MiB |
|    8   N/A  N/A     26601      C   ...da/envs/ps-mt/bin/python3     2869MiB |

`
I noticed that code used DistributedDataParallel.But why the first GPU(gpu 5) uses more GPU memory?How can I solve it?

**Comment by yyliu01** [comment]
Hi @Yan1026 ,

Could you please double check that you are working with DDP instead of DP?

Cheers,
Yuyuan

**Comment by yyliu01** [comment]
I'm closing the issue but feel free to reopen it if my answer doesn't solve your issue.
