### ISSUE TITLE
How to set wandb offline？

### ISSUE THREAD

**Issue by jjjsyyy** [yyliu01/PS-MT#23]
Hello!
  Can I know how to set wandb offline？ Because my school doesn't support me to use it online. 
  But when I set it offline according to someone else's method, it will report the following error.

  wandb: Network error (ReadTimeout), entering retry loop.

  Thank you very much!

**Comment by yyliu01** [comment]
Hi @jjjsyyy,

Please set it to be "disabled" in [here](https://github.com/yyliu01/PS-MT/blob/61d566e5670b900087a85f1e6021584c168122a9/VocCode/Utils/tensor_board.py#L16). 

Cheers,
Yuyuan
