### ISSUE TITLE
city_splits

### ISSUE THREAD

**Issue by alittledou** [yyliu01/PS-MT#28]
In city_splits ,the file name of gtFine is different from the name of city Raw data set. 
For example,In city_splits ,
/images/city_gt_fine/val/frankfurt_000001_066574_leftImg8bit.png /annotation/city_gt_fine/val/frankfurt_000001_066574_gtFine.png
In city Raw data set ,
stuttgart_000000_000019_gtFine_color.png

How can I get a city_splits dataset？

**Comment by yyliu01** [comment]
You can access our dataset in https://drive.google.com/file/d/1QNW_qRtCnL_Gn0blmHzxblfORCatiZb_/view?usp=share_link.

Please note, our cityscapes dataset following CPS and the lists of train/val IDs matches them (https://github.com/charlesCXK/TorchSemiSeg/blob/main/docs/getting_started.md).

**Comment by alittledou** [comment]
你好，这是自动回复邮件。你的邮件我已收到，我将尽快给你回复。

**Comment by alittledou** [comment]
> 

Thank you very much!!

**Comment by yyliu01** [comment]
@alittledou You're welcome.
