### ISSUE TITLE
Training with multi-GPUs

### ISSUE THREAD

**Issue by GuGuLL123** [yyliu01/PS-MT#3]
The code works fine when I train with one gpu.
The _warm_up process works fine when using multi-gpus distributed training，but the _train_epoch process gets stuck. Gpus and cpus are still running normally. Have you encountered the same problem?

**Comment by yyliu01** [comment]
Thanks for your interest.

No, I didn't meet such issues...  Could you please provide more training details, including batch size, and resolution? Also, could you please point out which parts of the code cause such stuck?

Regards,
Yuyuan Liu

**Comment by yyliu01** [comment]
I've found a pential issue in [here](https://github.com/yyliu01/PS-MT/blob/502ddfc1673c124235c5922a4338be795a4d34ff/CityCode/Utils/losses.py#L314). In case there isn't any confident pseudo-mask for 1 GPU, and another GPU will infinitely hangs in the backward process. 
Please modify it based on the newest code, and I apologize for the inconvenience.

**Comment by GuGuLL123** [comment]
thank you very much！ 
I will try it now.

**Comment by yyliu01** [comment]
I'm closing the issue. 

If you have any questions for implementing the code or reproducing the result, please feel free to reopen it or send me an email.

Regards,
Yuyuan
