### ISSUE TITLE
Stop issue

### ISSUE THREAD

**Issue by DeepHM** [yyliu01/PS-MT#30]
![image](https://user-images.githubusercontent.com/37736774/233086637-a0c993d3-5931-4ddd-87fb-32cb2b01b3f3.png)

Stops during learning. Do you know why?

**Comment by yyliu01** [comment]
Hi @DeepHM ,

Sorry for the late response, I was busy for some other projects. Could you provide the settings including batch size, dataset, and environments?

Cheers,
Yuyuan
