### ISSUE TITLE
Question about only supervised training

### ISSUE THREAD

**Issue by abhij247** [yyliu01/PS-MT#31]
Hey, I was trying to train the VOC model using only supervised learning, so I changed supervised = True and semi = False in deeplabv3+ config and only gave a labeled text file but I am not able to train it. What other changes should I do?

**Comment by yyliu01** [comment]
Hi @abhij247 

Could you please provide more details about the error feedback from the code? 

Why didn't you just simply set the unsupervised weight to 0? I know there are some differences about the batch norm layers for the unlabelled data, but it shouldn't be a big deal.

Cheers,
Yuyuan

**Comment by abhij247** [comment]
Thanks, I have set the unsupervised weight to 0 for the supervised training.
