### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by 836469383** [yyliu01/PS-MT#34]
First of all, the author is really good. This is a great job. Then the rookie wants a visual script. Any help will be greatly appreciated！

**Comment by yyliu01** [comment]
Hi @836469383,

The visualisation can be performed via matplotlib package in python.

```bash
import matplotlib.pyplot as plt
# for the label y with dimension H x W
plt.imshow(y)
plt.show()

# for the prediction with dimension class x H x W
plt.imshow(torch.argmax(y_hat, dim=0))
plt.show()
```

Cheers,
Yuyuan

**Comment by 836469383** [comment]
Thanks a lot! And sorry to bother you, but there's one small Q: what is the VT, and where can I find its code? thanks again
![image](https://github.com/yyliu01/PS-MT/assets/32611043/7a3cbbed-e2c5-4730-91be-4a328b46bfe1)

**Comment by yyliu01** [comment]
Hi @836469383 The AT denotes the assistance teaching, which means the ensemble prediction for the pseudo-label, refers to the code in [here](https://github.com/yyliu01/PS-MT/blob/61d566e5670b900087a85f1e6021584c168122a9/VocCode/train.py#L229).

**Comment by 836469383** [comment]
谢谢带佬，祝您工作顺利，生活愉快，祝好~

**Comment by yyliu01** [comment]
老哥不用客气
