### ISSUE TITLE
Question about the Conf-CE loss

### ISSUE THREAD

**Issue by Hugo-cell111** [yyliu01/PS-MT#35]
Hi! Have you done the experiments between the conf-based loss and normal ce loss and seen whether the difference exists?

**Comment by yyliu01** [comment]
Hi @Hugo-cell111 

In our experiments, conf-CE yields slight better performance (~0.5%) than the normal one in the low-quality labelled data setup with (1323) 1/8 partition protocol.

Cheers,
Yuyuan
