### ISSUE TITLE
about The results on classic val set based on resnet 50 as backbone?

### ISSUE THREAD

**Issue by yang654123** [yyliu01/PS-MT#36]
hi ,thank you for your nice work!
i have a question about the results on classic val set based on resnet 50 as backbone,so do you have it?
thanks a lot.

**Comment by yyliu01** [comment]
Hi @yang654123,

The result of ResNet50 has been reported in Table 1 & 2 of the main paper. Is that what you want?

Cheers,
Yuyuan

**Comment by yang654123** [comment]
> Hi @yang654123,
> 
> The result of ResNet50 has been reported in Table 1 & 2 of the main paper. Is that what you want?
> 
> Cheers, Yuyuan

sorry，i want the results of classic val set based on resnet50 not blender val set.

**Comment by yyliu01** [comment]
Hi @yang654123 

I'm confused, I think the validation dataset should be unique for all set-up.
In case you are talking about the training set, the ResNet50 results are reported in Table 3.

Could you please provide more details, like which partition protocol or which dataset you are talking about.

Cheers,
Yuyuan

**Comment by yang654123** [comment]
> 
sorry, i mean the results of 1464labels origin high resolution dataset which also named of classic dataset ,also called official dataset.

**Comment by yang654123** [comment]
> Hi @yang654123
> 
> I'm confused, I think the validation dataset should be unique for all set-up. In case you are talking about the training set, the ResNet50 results are reported in Table 3.
> 
> Could you please provide more details, like which partition protocol or which dataset you are talking about.
> 
> Cheers, Yuyuan
haha I see,but do you have other results on particial protocol like 92,183,366,732 and so on .

**Comment by yyliu01** [comment]
Hi @yang654123 

The 1464 labels results under ResNet50 are in Tab 3, while we only have resnet101 results for the splits you mentioned, as we followed CPS table. 
Sorry for the inconvenience.

Cheers,
Yuyuan
