### ISSUE TITLE
three teachers

### ISSUE THREAD

**Issue by wangmingaaaaa** [yyliu01/PS-MT#38]
Would it be better to integrate three teachers?

**Comment by yyliu01** [comment]
Hi @wangmingaaaaa 

Unfortunately, no. I have tried it, but the performance did not show significant improvement with more than two teachers. The potential reason might be that they eventually converge to the same local minimum in the late stages of training, and more teachers speed up such process. 

While a potential solution is a different optimisation way of the third teacher, and this [paper](https://openaccess.thecvf.com/content_CVPR_2019/papers/Liu_Structured_Knowledge_Distillation_for_Semantic_Segmentation_CVPR_2019_paper.pdf) might be relevant.

Cheers,
Yuyuan

**Comment by wangmingaaaaa** [comment]
Thank you very much for your reply
