### ISSUE TITLE
CutMix for Cityscapes

### ISSUE THREAD

**Issue by JoyHuYY1412** [yyliu01/PS-MT#4]
Hi, thank you for your work. I have a question about the CuTMIx. 

Since the batch size for each GPU is 1 when using 8GPUs (conventional setting), I wonder how to perform CutMix when only one unlabeled image is in a GPU? Can you give me some advice?

**Comment by yyliu01** [comment]
Thanks for your interest.

1). If the single GPU has enough memory for the mixed regions (which are cut from the other GPUs' unlabelled data), then you can perform all_gather for the inter-communication in the cluster. But, the speed will be dramatically slowed down I guess.

2). If it cannot handle the mixed region,  then I have no idea for this situation. 

Regards,
Yuyuan

**Comment by JoyHuYY1412** [comment]
> Thanks for your interest.
> 
> 1). If the single GPU has enough memory for the mixed regions (which are cut from the other GPUs' unlabelled data), then you can perform all_gather for the inter-communication in the cluster. But, the speed will be dramatically slowed down I guess.
> 
> 2). If it cannot handle the mixed region, then I have no idea for this situation.
> 
> Regards, Yuyuan

Thank you. According to your training script, you used two gpus with 4 labeled and 4 unlabeled each gpu. Did I understood right?

**Comment by yyliu01** [comment]
Hi Joy,

You can find my training details through this link (https://wandb.ai/pyedog1976/PS-MT(VOC12)?workspace=user-pyedog1976) and this one (https://wandb.ai/pyedog1976/PS-MT(City)?workspace=user-pyedog1976). 

You can click the experiment name and find out details in the **overview** and **hardware** tags (e.g., in [here](https://wandb.ai/pyedog1976/PS-MT(VOC12)/runs/1k3m5qgb/overview?workspace=user-pyedog1976)).

Regards,
Yuyuan
