### ISSUE TITLE
my god !!!! this code is too  abstract ..........

### ISSUE THREAD

**Issue by Wzhengkai** [yyliu01/PS-MT#41]
"Hey, buddy,  this code seems overly complicated. I wondering why it's been encapsulated in so many layers. It's frustrating when I encounter numerous errors while trying to run it with a different dataset. Modifying it becomes quite exhausting. Why wasn't the code simplified before sharing it?"

**Comment by yyliu01** [comment]
Hi @Wzhengkai 

Sorry for the inconvenience. The code are partially adopted from CPS (https://github.com/charlesCXK/TorchSemiSeg) and CCT (https://github.com/yassouali/CCT), and yes, it contains some duplicated modules that can be further simplified.

Cheers,
Yuyuan
