### ISSUE TITLE
about network

### ISSUE THREAD

**Issue by ruizes** [yyliu01/PS-MT#42]
Hello.
Can I know why you choose the two teacher networks,Can I replace a teacher network with a network whose parameters are updated independently using SGD? 

Thank you !

**Comment by yyliu01** [comment]
Hi @ruizes 

I apologise for the late reply, I was in a travel. 

1). The two teachers based structure can improve the reliance of the pseudo label and further improve the generalisation when they meet the hard unlabelled samples. 

2). Yes, you can.

Thanks for your interest.

Cheers,
Yuyuan

**Comment by ruizes** [comment]
Thank you for your reply. Have a great trip!
