### ISSUE TITLE
About training config

### ISSUE THREAD

**Issue by Yan1026** [yyliu01/PS-MT#9]
Hi,thank you for your great work!
If I use 4GPU,and batchsize=16 learning-rate=1e-2 ,will it be the best configuration?

And why you said 2GPU can get better performance rather than 4GPU?

**Comment by yyliu01** [comment]
Hi,

I've only tested the 1464 high-quality setting with 2GPUs, and it outperforms the paper results by about 1 point. Please follow the settings in here (https://wandb.ai/pyedog1976/PS-MT(VOC12)/runs/23b8qul0/overview?workspace=user-pyedog1976). 

I haven't tested it for the aug setting, so it will be safe to run the setting provided by the scripts.

Regards,
Yuyuan

**Comment by Yan1026** [comment]
I run with ./scripts/train_voc_aug.sh -l 1323 -g 4 -b 101   but get error：



ID 3 Warm (4) | Ls 0.51 |:  98%|█████████████████████████████████████████████████████████████████████▎ | 40/41 [01:04<00:00,  1.18it/s]
ID 3 Warm (4) | Ls 0.51 |:  98%|█████████████████████████████████████████████████████████████████████▎ | 40/41 [01:14<00:00,  1.18it/s]
ID 3 Warm (4) | Ls 0.51 |: 100%|███████████████████████████████████████████████████████████████████████| 41/41 [01:14<00:00,  3.65s/it]
ID 3 Warm (4) | Ls 0.51 |: 100%|███████████████████████████████████████████████████████████████████████| 41/41 [01:14<00:00,  1.81s/it]

  0%|                                                                                                          | 0/289 [00:00<?, ?it/s]wandb: Network error (ConnectionError), entering retry loop.

How can I solve this problem？

**Comment by yyliu01** [comment]
It doesn't need to be fixed. Wandb sometimes encounters network traffic issues, but it will be reconnected automatically and will not affect the training.
